
-- /= = = = = = = = = = = = = = = = = = = = =
-- for the test of uneven common column
-- = = = = = = = = = =/
CREATE TABLE WHITE_UNEVEN_COMMON_COLUMN_1ST (
	UNEVEN_ID INTEGER NOT NULL,
	UNEVEN_NAME VARCHAR(200) NOT NULL,
	REGISTER_DATETIME DATETIME NOT NULL,
	PRIMARY KEY(UNEVEN_ID)
);

CREATE TABLE WHITE_UNEVEN_COMMON_COLUMN_2ND (
	UNEVEN_ID INTEGER NOT NULL,
	UNEVEN_NAME VARCHAR(200) NOT NULL,
	REGISTER_DATETIME DATETIME NOT NULL,
	REGISTER_USER VARCHAR(200) NOT NULL,
	PRIMARY KEY(UNEVEN_ID)
);

CREATE TABLE WHITE_UNEVEN_COMMON_COLUMN_3RD (
	UNEVEN_ID INTEGER NOT NULL,
	UNEVEN_NAME VARCHAR(200) NOT NULL,
	REGISTER_DATETIME DATETIME NOT NULL,
	UPDATE_DATETIME DATETIME NOT NULL,
	PRIMARY KEY(UNEVEN_ID)
);

CREATE TABLE WHITE_UNEVEN_COMMON_COLUMN_4TH (
	UNEVEN_ID INTEGER NOT NULL,
	UNEVEN_NAME VARCHAR(200) NOT NULL,
	REGISTER_DATETIME DATETIME NOT NULL,
	REGISTER_USER VARCHAR(200) NOT NULL,
	UPDATE_DATETIME DATETIME NOT NULL,
	PRIMARY KEY(UNEVEN_ID)
);
